### PR TITLE
Add examples to schemas

### PR DESCRIPTION
**Pull request by tojump**
As the name indicates this PR adds examples to the object schemas.

The example were collected and adapted manually from the various Chia RPC docs, so there is the potential for some inaccuracies but from a quick review I didn't spot anything obviously wrong.

Similarly the https://www.npmjs.com/package/yaml parsing modified the formatting slightly.

### CODE REVIEW

**Comment by tojump** [comment]
Note that I didn't commit the updated `docs` folder as I am not certain of the procedure for building.

**Review by dkackman — COMMENTED** [review]
This is great! I am looking through them.

Can you let me know what the `annotate-with-example.zx.mjs` does and add comments to the top of that file?

**Comment by tojump** [comment]
> Can you let me know what the `annotate-with-example.zx.mjs` does and add comments to the top of that file?

It's the script I used to insert examples into the existing schemas.
We can use it by piping the example data corresponding to the given schema file. For instance:

```bash
cat <<EOF | ./tools/annotate-with-example.zx.mjs src/schemas/network_info.yaml
{
    "network_name": "mainnet",
    "network_prefix": "xch",
    "success": true
}
EOF
```

It doesn't necessarily need to be committed because it doesn't need to be run again, but I included it for documentation purposes and in the case where we wanted to tweak the output or feed a different example.

**Comment by dkackman** [comment]
> > Can you let me know what the `annotate-with-example.zx.mjs` does and add comments to the top of that file?
> 
> It's the script I used to insert examples into the existing schemas. We can use it by piping the example data corresponding to the given schema file. For instance:
> 
> ```shell
> cat <<EOF | ./tools/annotate-with-example.zx.mjs src/schemas/network_info.yaml
> {
>     "network_name": "mainnet",
>     "network_prefix": "xch",
>     "success": true
> }
> EOF
> ```
> 
> It doesn't necessarily need to be committed because it doesn't need to be run again, but I included it for documentation purposes and in the case where we wanted to tweak the output or feed a different example.

Makes sense. Will add this to the top of that file for reference.

**Comment by tojump** [comment]
> Makes sense. Will add this to the top of that file for reference.

Ah, I just committed something like that 🙂

**Review by dkackman — APPROVED** [review]

**Comment by dkackman** [comment]
These are published. Been wanting to incorporate something like this for awhile. Thank you!

**Pull request merged**
